sudo: required
dist: trusty

language: cpp

addons: &g++6
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6

matrix:
  include:
    - env: GCC_VERSION=6
      addons: *g++6

script:
  - mkdir .build
  - cd .build
  - cmake -DCMAKE_CXX_COMPILER=g++-${GCC_VERSION} ..
  - cmake --build .
  - ctest --verbose
