# # Adapted from various sources, including:
# - https://github.com/gabime/spdlog

sudo: required
dist: trusty

language: cpp

addons: &gcc48
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

addons: &gcc5
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5

addons: &gcc6
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6

addons: &gcc7
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7

addons: &gcc8
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8

addons: &gcc9
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-9

addons: &clang6
  apt:
    packages:
      - clang-6.0
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-6.0

matrix:
  include:
    # See https://github.com/approvals/ApprovalTests.cpp/issues/13 for fixing this build
    # - env: GCC_VERSION=4.8
    #   addons: *gcc48

    - env: GCC_VERSION=5
      addons: *gcc5

    - env: GCC_VERSION=6
      addons: *gcc6

    - env: GCC_VERSION=7
      addons: *gcc7

    - env: GCC_VERSION=8
      addons: *gcc8

    - env: GCC_VERSION=9
      addons: *gcc9

    - env: CLANG_VERSION=6.0
      addons: *clang6

before_script:
  - if [ -n "$GCC_VERSION" ]; then export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}"; fi
  - if [ -n "$CLANG_VERSION" ]; then export CXX="clang++-${CLANG_VERSION}" CC="clang-${CLANG_VERSION}"; fi
  - which $CXX
  - which $CC
  - $CXX --version
  - cmake --version

script:
  - mkdir .build
  - cd .build
  - cmake ..
  - cmake --build .
  - ctest --verbose
