sudo: required
dist: trusty

language: cpp

script:
  - mkdir .build
  - cd .build
  - cmake -DCMAKE_CXX_COMPILER=g++-6 ..
  - cmake --build .
  - ctest --verbose

matrix:
 include:

  - os: linux
    compiler: g++
    env: COMPILER=g++-6 BUILD=Debug ARCH=64
    addons:
     apt:
      sources:
       - ubuntu-toolchain-r-test
      packages:
       - g++-6