# Adapted from various sources, including:
# - https://github.com/gabime/spdlog

sudo: required
language: cpp

# -------------------------------------------------------------------------
# Linux gcc
# -------------------------------------------------------------------------

addons: &gcc48
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

addons: &gcc5
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5

addons: &gcc6
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6

addons: &gcc7
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7

addons: &gcc8
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8

addons: &gcc9
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-9

# -------------------------------------------------------------------------
# Linux clang
# -------------------------------------------------------------------------

addons: &clang5
  compiler: clang
  apt:
    packages:
      - clang-5.0
      - libstdc++-8-dev
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-5.0

addons: &clang6
  compiler: clang
  apt:
    packages:
      - clang-6.0
      - libstdc++-8-dev
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-6.0

matrix:
  include:
    
    # -------------------------------------------------------------------------
    # Linux gcc
    # -------------------------------------------------------------------------

    # See https://github.com/approvals/ApprovalTests.cpp/issues/13 for fixing this build
    # - env: GCC_VERSION=4.8
    #   addons: *gcc48

    - env: GCC_VERSION=5
      os: linux
      addons: *gcc5

    - env: GCC_VERSION=6
      os: linux
      addons: *gcc6

    - env: GCC_VERSION=7
      os: linux
      addons: *gcc7

    - env: GCC_VERSION=8
      os: linux
      addons: *gcc8

    - env: GCC_VERSION=9
      os: linux
      addons: *gcc9

    # -------------------------------------------------------------------------
    # Linux clang
    # -------------------------------------------------------------------------

    - env: CLANG_VERSION=5.0
      os: linux
      addons: *clang5

    - env: CLANG_VERSION=6.0
      os: linux
      addons: *clang6

    # -------------------------------------------------------------------------
    # Mac clang
    # -------------------------------------------------------------------------

    - os: osx
      osx_image: xcode8.3

    - os: osx
      osx_image: xcode9.4

    - os: osx
      osx_image: xcode10.2

before_script:
  - if [ -n "$GCC_VERSION" ]; then export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}"; fi
  - if [ -n "$CLANG_VERSION" ]; then export CXX="clang++-${CLANG_VERSION}" CC="clang-${CLANG_VERSION}"; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export CXX="clang++" CC="clang"; fi
  - which $CXX
  - which $CC
  - $CXX --version
  - cmake --version

script:
  - mkdir .build
  - cd .build
  - cmake ..
  - cmake --build .
  - ctest --verbose

notifications:
  email: true
