sudo: required
dist: trusty

language: cpp

addons: &g++5
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5

addons: &g++6
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6

addons: &g++7
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7

matrix:
  include:
    - env: GCC_VERSION=5
      addons: *g++5

    - env: GCC_VERSION=6
      addons: *g++6

    - env: GCC_VERSION=7
      addons: *g++7

script:
  - mkdir .build
  - cd .build
  - cmake -DCMAKE_CXX_COMPILER=g++-${GCC_VERSION} ..
  - cmake --build .
  - ctest --verbose
