sudo: required
dist: trusty

language: cpp

addons: &gcc48
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

addons: &gcc5
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5

addons: &gcc6
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6

addons: &gcc7
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7

addons: &gcc8
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8

addons: &gcc9
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-9

matrix:
  include:
    # See https://github.com/approvals/ApprovalTests.cpp/issues/13 for fixing this build
    # - env: GCC_VERSION=4.8
    #   addons: *gcc48

    - env: GCC_VERSION=5
      addons: *gcc5

    - env: GCC_VERSION=6
      addons: *gcc6

    - env: GCC_VERSION=7
      addons: *gcc7

    - env: GCC_VERSION=8
      addons: *gcc8

    - env: GCC_VERSION=9
      addons: *gcc9

script:
  - mkdir .build
  - cd .build
  - cmake -DCMAKE_CXX_COMPILER=g++-${GCC_VERSION} ..
  - cmake --build .
  - ctest --verbose
