image: Visual Studio 2017

#branches:
#  except:
#    - more_travis_builds

before_build:
- cmd: cmake .

build_script:
- cmd: cmake --build .

test_script:
- cmd: ctest --verbose --parallel 4 -C Debug
