environment:
  matrix:
    - TARGET: vs2017
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      GENERATOR: '"MSYS Makefiles"'

    - TARGET: vs2017
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      GENERATOR: '"Visual Studio 15 2017"'

    - TARGET: vs2019
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      GENERATOR: '"Visual Studio 16 2019"'

#branches:
#  except:
#    - more_travis_builds

before_build:
- cmd: |
    echo %PATH%
    set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
    echo %PATH%
    set PATH=C:\MinGW\bin;%PATH%
    echo %PATH%
    cmake --help
    cmake -G %GENERATOR% .

build_script:
- cmd: cmake --build .

test_script:
- cmd: ctest --verbose --parallel 4 -C Debug
